"""empty message

Revision ID: 37516dbc91a4
Revises: 655a042d232a
Create Date: 2021-01-28 17:03:32.837405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37516dbc91a4'
down_revision = '655a042d232a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TempClifor', sa.Column('cd_vendedor', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TempClifor', 'cd_vendedor')
    # ### end Alembic commands ###
