"""empty message

Revision ID: 655a042d232a
Revises: 83b313d88bbb
Create Date: 2021-01-27 17:26:56.687041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655a042d232a'
down_revision = '83b313d88bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TempClifor', 'dt_altera')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TempClifor', sa.Column('dt_altera', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
