"""empty message

Revision ID: b04ad51960d8
Revises: 6a72d4a18ea0
Create Date: 2021-01-22 13:22:59.111454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04ad51960d8'
down_revision = '6a72d4a18ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabpre_cli', sa.Column('vl_percmax', sa.String(length=10), nullable=True))
    op.add_column('tabpre_cli', sa.Column('vl_percmin', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabpre_cli', 'vl_percmin')
    op.drop_column('tabpre_cli', 'vl_percmax')
    # ### end Alembic commands ###
