"""empty message

Revision ID: c17781ca132d
Revises: 37516dbc91a4
Create Date: 2021-02-01 11:36:41.883368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17781ca132d'
down_revision = '37516dbc91a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('ds_observ', sa.String(length=250), nullable=True))
    op.drop_column('pedido', 'ds_obersv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('ds_obersv', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('pedido', 'ds_observ')
    # ### end Alembic commands ###
